# Generated by Django 2.2 on 2022-04-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20220429_1049'),
        ('app_news', '0002_auto_20220429_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_auth_user_name', models.CharField(default=None, max_length=30, null=True, verbose_name='Имя пользователя')),
                ('user_comment', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Комментарий')),
                ('news', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='app_news.News', verbose_name='Новости')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Profile', verbose_name='Имя пользователя')),
            ],
        ),
    ]
