# Generated by Django 2.2 on 2022-05-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(max_length=200, null=True, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Profile', verbose_name='Профиль пользователя'),
        ),
    ]
