# Generated by Django 2.2 on 2022-04-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can verify', 'может верифицировать'),)},
        ),
    ]
