# Generated by Django 2.2 on 2022-06-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Good',
        ),
    ]
