# Generated by Django 2.2 on 2022-06-14 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app_shops.Shop', verbose_name='магазин'),
            preserve_default=False,
        ),
    ]
