# Generated by Django 2.2 on 2022-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_good_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-id'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.RemoveField(
            model_name='good',
            name='shop',
        ),
        migrations.AddField(
            model_name='good',
            name='shops',
            field=models.ManyToManyField(related_name='goods', to='app_shops.Shop', verbose_name='магазины'),
        ),
    ]
