# Generated by Django 2.2 on 2022-05-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(max_length=2000, verbose_name='Содержание статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tags', models.CharField(max_length=200, null=True, verbose_name='Тег')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Profile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['created_at'],
            },
        ),
    ]
