# Generated by Django 2.2 on 2022-05-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_auto_20220514_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='app_blog.Blog', verbose_name='Файлы к статье'),
        ),
    ]
