# Generated by Django 2.2 on 2022-03-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20220304_1427'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='ads_advertisement',
        ),
    ]
