# Generated by Django 2.2 on 2022-03-05 07:13

from django.db import migrations


def combine_ads(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Advertisement = apps.get_model('ads', 'Advertisement')
    for num in range(1, 500000):
        Advertisement.objects.create(title=f'Сгенерированное объявление{num}')


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20220304_1428'),
    ]

    operations = [
        migrations.RunPython(combine_ads),
    ]
