# Generated by Django 2.2 on 2022-03-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20220305_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='ads.AdvertisementStatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Заголовок'),
        ),
    ]
