# Generated by Django 2.2 on 2022-03-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20220309_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='closed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата окончания публикации.'),
        ),
    ]
