# Generated by Django 2.2 on 2022-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='personal_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
