# Generated by Django 2.2 on 2022-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_auto_20220321_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('r', 'Review'), ('p', 'Published')], default='d', max_length=1),
        ),
    ]
