# Generated by Django 2.2 on 2022-03-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20220314_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('n', 'Not_Published')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='app_news.News', verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
