# Generated by Django 2.2 on 2022-03-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20220322_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
    ]
