# Generated by Django 2.2 on 2022-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_remove_news_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('a', 'Активен'), ('d', 'УдаленоАдминистратором')], default='a', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('p', 'Опубликован'), ('n', 'Неопубликован')], default='n', max_length=1, verbose_name='Статус'),
        ),
    ]
