# Generated by Django 2.2 on 2022-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20220328_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
