# Generated by Django 2.2 on 2022-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_comment_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.CharField(max_length=2000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
