# Generated by Django 2.2 on 2022-05-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0004_auto_20220530_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='total',
        ),
        migrations.AddField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
