# Generated by Django 2.2 on 2022-05-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_name',
            new_name='username',
        ),
    ]
