# Generated by Django 2.2 on 2022-05-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['id'], 'verbose_name': 'файл', 'verbose_name_plural': 'файлы'},
        ),
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_blog.File', verbose_name='Файлы к статье'),
            preserve_default=False,
        ),
    ]
